### ISSUE TITLE
ftPosSystemId - Please improve handling

### ISSUE THREAD

**Issue by Lorscheidt** [fiskaltrust/middleware-interface-dotnet#25] opened 2020-09-11 13:18 UTC
Hi there,

Feeding in the ftPosSystemId is a very tedious process and impossible to get a 100% synced with server / client releases.
We'd suggest to pass the version on in every request.

**Comment by StefanKert** [comment] 2020-09-18 08:18
Closed as this is a duplicate of https://github.com/fiskaltrust/interface-doc/issues/114

**Closed by StefanKert** 2020-09-18 08:18 UTC
