### ISSUE TITLE
Fiskaltrust Middleware installation issue on macOS

### ISSUE THREAD

**Issue by anceschim** [fiskaltrust/middleware-interface-dotnet#40] opened 2021-04-08 13:11 UTC
We need to install the middleware on OSX/macOS environment (on different versions, starting from 10.9 to the latest).

Of course, we followed the directions for Unix-like systems, but on all OSX version we have a failure when trying to download fiskaltrust.Middleware.Helper.Helipad (Version: 1.3.11) from https://packages-sandbox.fiskaltrust.cloud/nuget/.
Please note that there are no network restrictions (like proxy/firewall), since we used a public internet connection to avoid any possible network issues.

I'm attaching the whole log, so that you can easily read through it.
(here in the first lines you can see also the problem on issue #39 , regarding a problem about SIP...but we think this is another matter)  

[fiskaltrust_log.txt](https://github.com/fiskaltrust/middleware-interface-dotnet/files/6278857/fiskaltrust_log.txt)

**Comment by TSchmiedlechner** [comment] 2021-04-12 11:46
Dear @anceschim,
I think I just responded to your question via email, but for traceability reasons: I think this issue is caused by the underlying error you described in #39. As written in line 9 of the log file, the Middleware is still not able to access the respective directory:

```log
System.UnauthorizedAccessException: Access to the path '/usr/share/fiskaltrust/service' is denied. ---> System.IO.IOException: Operation not permitted
```

I'd recommend to select a accessible directory with the `-servicefolder` parameter, as described in our [docs](https://docs.fiskaltrust.cloud/docs/poscreators/middleware-doc/general/installation) - IMO this should also resolve the follow-up issues.

**Comment by anceschim** [comment] 2021-04-13 14:37
Thanks Tom for your kind explanation.
We've successfully used the config you're pointing to (sorry we didn't understand -servicefolder in this way).
I can confirm that the error is gone, but we're experiencing another error related to file system, so I continue on.
Here is the log of the installation (some rows "anonymized"):


OSX:fiskaltrust.service.launcher.ec012d45-72a8-4c39-9676-108ac5dccb66 home$ ./test.sh
2021-04-13 13:45:45 [INF] fiskaltrust.Launcher-1.3.14
2021-04-13 13:45:45 [INF] CashBoxId set to "ec012d45-72a8-4c39-9676-108ac5dccb66"
2021-04-13 13:45:45 [INF] AccessToken set
2021-04-13 13:45:45 [INF] Service folder set to "/users/negozio/documents"
2021-04-13 13:45:45 [INF] SSLValidation set to "False"
2021-04-13 13:45:45 [INF] Sandbox set to "True"
2021-04-13 13:45:47 [INF] Downloading fiskaltrust.Middleware.Helper.Helipad 1.3.11 updates to BasePath /users/negozio/documents/ec012d45-72a8-4c39-9676-108ac5dccb66 ....
2021-04-13 13:45:52 [INF] Download done!
2021-04-13 13:45:52 [INF] Downloading fiskaltrust.Middleware.SCU.DE.Fiskaly 1.3.14-rc1 updates to BasePath /users/negozio/documents/ec012d45-72a8-4c39-9676-108ac5dccb66 ....
2021-04-13 13:45:57 [INF] Download done!
2021-04-13 13:45:57 [INF] Downloading fiskaltrust.Middleware.Queue.SQLite 1.3.14 updates to BasePath /users/negozio/documents/ec012d45-72a8-4c39-9676-108ac5dccb66 ....
2021-04-13 13:46:05 [INF] Download done!
2021-04-13 13:46:05 [INF] Rename fiskaltrust.Middleware.Helper.Helipad 1.3.11 updates ....
2021-04-13 13:46:05 [INF] Rename fiskaltrust.Middleware.SCU.DE.Fiskaly 1.3.14-rc1 updates ....
2021-04-13 13:46:05 [INF] Rename fiskaltrust.Middleware.Queue.SQLite 1.3.14 updates ....
2021-04-13 13:46:05 [INF] Save configuration to /users/negozio/documents/Configuration-ec012d45-72a8-4c39-9676-108ac5dccb66.json
2021-04-13 13:46:05 [INF] Starting ft.Middleware at /users/negozio/documents/ec012d45-72a8-4c39-9676-108ac5dccb66
2021-04-13 13:46:05 [INF] Loading Helper Id c32204ee-63d9-48c2-b548-acfb389fa713 from Package fiskaltrust.Middleware.Helper.Helipad, Version 1.3.11
2021-04-13 13:46:07 [INF] Create Helper c32204ee-63d9-48c2-b548-acfb389fa713
2021-04-13 13:46:07 [INF] Loading SecureSignaturCreationDevice Id 8588148e-2d8d-48ab-a0fd-5d0ed2276558 from Package fiskaltrust.Middleware.SCU.DE.Fiskaly, Version 1.3.14-rc1
2021-04-13 13:46:08 [INF] Create SecureSignaturCreationDevice 8588148e-2d8d-48ab-a0fd-5d0ed2276558
2021-04-13 13:46:08 [ERR] Failed to setup SecureSignaturCreationDevice Id 8588148e-2d8d-48ab-a0fd-5d0ed2276558 from Package fiskaltrust.Middleware.SCU.DE.Fiskaly, Version 1.3.14-rc1
System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: /Users/negozio/Desktop/fiskaltrust/fiskaltrust.service.launcher.ec012d45-72a8-4c39-9676-108ac5dccb66/libgrpc_csharp_ext.x64.dylib,/Users/negozio/Desktop/fiskaltrust/fiskaltrust.service.launcher.ec012d45-72a8-4c39-9676-108ac5dccb66/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib,/Users/negozio/Desktop/fiskaltrust/fiskaltrust.service.launcher.ec012d45-72a8-4c39-9676-108ac5dccb66/../../runtimes/osx/native/libgrpc_csharp_ext.x64.dylib


Server stack trace:
  at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath (System.String[] libraryPathAlternatives) [0x00042] in <7d3022cde3f7402ca9f9514161a92158>:0
  at Grpc.Core.Internal.UnmanagedLibrary..ctor (System.String[] libraryPathAlternatives) [0x00006] in <7d3022cde3f7402ca9f9514161a92158>:0
  at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary () [0x00044] in <7d3022cde3f7402ca9f9514161a92158>:0
  at Grpc.Core.Internal.NativeExtension.LoadNativeMethods () [0x0001a] in <7d3022cde3f7402ca9f9514161a92158>:0
  at Grpc.Core.Internal.NativeExtension..ctor () [0x00006] in <7d3022cde3f7402ca9f9514161a92158>:0
  at Grpc.Core.Internal.NativeExtension.Get () [0x00022] in <7d3022cde3f7402ca9f9514161a92158>:0
  at Grpc.Core.Internal.NativeMethods.Get () [0x00000] in <7d3022cde3f7402ca9f9514161a92158>:0
  at Grpc.Core.GrpcEnvironment.GrpcNativeInit () [0x00016] in <7d3022cde3f7402ca9f9514161a92158>:0
  at Grpc.Core.GrpcEnvironment..ctor () [0x0001e] in <7d3022cde3f7402ca9f9514161a92158>:0
  at Grpc.Core.GrpcEnvironment.AddRef () [0x00028] in <7d3022cde3f7402ca9f9514161a92158>:0
  at Grpc.Core.Server..ctor (System.Collections.Generic.IEnumerable`1[T] options) [0x0006d] in <7d3022cde3f7402ca9f9514161a92158>:0
  at Grpc.Core.Server..ctor () [0x00000] in <7d3022cde3f7402ca9f9514161a92158>:0
  at fiskaltrust.service.launcher.Helpers.Grpc.GrpcHelper.StartHost (System.String url, System.Type type, System.Object service, Microsoft.Extensions.DependencyInjection.IServiceCollection services, Grpc.Core.ServerCredentials serverCredentails) [0x00007] in <a905ad260aa841eabb33fbe2f4245f94>:0
  at fiskaltrust.service.launcher.Helpers.Grpc.GrpcHost.StartService (fiskaltrust.storage.serialization.V0.PackageConfiguration config, System.String url, System.Type type, System.Object service) [0x00035] in <a905ad260aa841eabb33fbe2f4245f94>:0
  at fiskaltrust.service.launcher.Helpers.HostingHelper.SetupServiceForObject (fiskaltrust.storage.serialization.V0.PackageConfiguration config, System.Object serviceInstance, Microsoft.Extensions.DependencyInjection.IServiceCollection services) [0x0009a] in <a905ad260aa841eabb33fbe2f4245f94>:0
  at fiskaltrust.service.launcher.NutShell.SSCDNutShell.Start (fiskaltrust.storage.serialization.V0.PackageConfiguration configuration) [0x0006e] in <a905ad260aa841eabb33fbe2f4245f94>:0
  at (wrapper remoting-invoke-with-check) fiskaltrust.service.launcher.NutShell.SSCDNutShell.Start(fiskaltrust.storage.serialization.V0.PackageConfiguration)
  at (wrapper xdomain-dispatch) fiskaltrust.service.launcher.NutShell.SSCDNutShell.Start(object,byte[]&,byte[]&)

Exception rethrown at [0]:
  at (wrapper xdomain-invoke) fiskaltrust.service.launcher.NutShell.SSCDNutShell.Start(fiskaltrust.storage.serialization.V0.PackageConfiguration)
  at (wrapper remoting-invoke-with-check) fiskaltrust.service.launcher.NutShell.SSCDNutShell.Start(fiskaltrust.storage.serialization.V0.PackageConfiguration)
  at fiskaltrust.service.launcher.ftService.SetupSSCD (fiskaltrust.storage.serialization.V0.PackageConfiguration item) [0x000b5] in <a905ad260aa841eabb33fbe2f4245f94>:0
2021-04-13 13:46:08 [ERR] Error launching Middleware, retry in 15s with download! (Error loading native library. Not found in any of the possible locations: /Users/negozio/Desktop/fiskaltrust/fiskaltrust.service.launcher.ec012d45-72a8-4c39-9676-108ac5dccb66/libgrpc_csharp_ext.x64.dylib,/Users/negozio/Desktop/fiskaltrust/fiskaltrust.service.launcher.ec012d45-72a8-4c39-9676-108ac5dccb66/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib,/Users/negozio/Desktop/fiskaltrust/fiskaltrust.service.launcher.ec012d45-72a8-4c39-9676-108ac5dccb66/../../runtimes/osx/native/libgrpc_csharp_ext.x64.dylib)
System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: /Users/negozio/Desktop/fiskaltrust/fiskaltrust.service.launcher.ec012d45-72a8-4c39-9676-108ac5dccb66/libgrpc_csharp_ext.x64.dylib,/Users/negozio/Desktop/fiskaltrust/fiskaltrust.service.launcher.ec012d45-72a8-4c39-9676-108ac5dccb66/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib,/Users/negozio/Desktop/fiskaltrust/fiskaltrust.service.launcher.ec012d45-72a8-4c39-9676-108ac5dccb66/../../runtimes/osx/native/libgrpc_csharp_ext.x64.dylib

**Comment by anceschim** [comment] 2021-04-22 15:54
Hello @TSchmiedlechner , any news on that?
May I help you in some way? If you need to, we can reply this problem, do other tests or give you any info.
Best

**Comment by TSchmiedlechner** [comment] 2021-05-10 14:07
Hi @anceschim, my sincere apologies for the late response. It seems like the gRPC library our Middleware uses cannot be loaded properly on the used operating system - this might be due to a temporary issue in our package server that has been resolved a few days ago. Would you have the chance to retry downloading the Launcher from the Portal after a rebuild?

**Comment by TSchmiedlechner** [comment] 2021-06-15 08:08
Closing this now, please reopen if the issue still exists. Thank you 🙂

**Closed by TSchmiedlechner** 2021-06-15 08:08 UTC
